install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

configuration: Release

after_build:
  - nuget pack JsonLd.Entities.nuspec -Version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  
artifacts:
  - path: JsonLd.Entities.%GitVersion_NuGetVersion%.nupkg
  
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/tpluscode78631-6jxuo30rn51k
  api_key:
    secure: i9B4FzSsIyRHv57fkSaH97JiI7jwQL+FC1WSal2lR0E=
  artifact: JsonLd.Entities.%GitVersion_NuGetVersion%.nupkg