before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

configuration: Release

on_success:
  - nuget pack JsonLd.Entities.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "JsonLd.Entities.$($env:APPVEYOR_BUILD_VERSION).nupkg"