install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

configuration: Release

after_build:
  - nuget pack JsonLd.Entities.nuspec -Version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  
artifacts:
  - path: '*.nupkg'
